<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
  [ {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "澳麒酒业",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "TANK 城市会客厅",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "百乐庄",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "港口灌装基地",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  } ]
  </script>
    <meta name="description" content="Orchid Group |Wine Estate |TANK 城市会客厅 |Blickinstal |Harbour Bottling |Orchid Group Home | 澳麒酒业集团首页">
    <meta name="description" content="Orchid Group |澳麒酒业 |TANK 城市会客厅 |百乐庄 |港口灌装基地 |Orchid Group Home | 澳麒酒业集团首页">
    <meta name="description" content="位于阿德莱德CBD的澳麒酒业总部，承担着“业务洽谈，产品设计，生产调度，市场推广，企业培训”等业务。办公室地处阿德莱德市区的黄金地段，位于阿德莱德Gouger
  St的208号，占地210平方米，毗邻澳州邮政的物流中心，交通十分便利，距离阿德莱德机场也仅5公里路程，是开展国际贸易的最佳地段。">
    <meta name="description" content="全球首家TANK选址于世界十大葡萄酒之都的阿德莱德。TANK成立的初衷，就是为了向全世界的酒类爱好者，更好的介绍和推荐来自于南澳地区的精品葡萄酒，啤酒以及烈酒。南澳，作为一个充满活力的葡萄酒产区，拥有众多世界闻名的子产区，如巴罗莎等。得天独厚的条件，使得这个地区佳酿频出。因此，TANK致力于向全世界的广大消费者传播南澳的葡萄酒文化以及葡萄酒酿造工艺，与此同时，更是为了将每一款的好酒带到您的面前。">
    <meta name="description" content="澳麒百乐葡萄园及产品研发心Blickinstal，是位于巴罗莎山谷的核心产区酒庄，是澳麒的产品体验以及研发中心。Blickinstal民宿，连续3年被澳州评为5星级B&B
  民宿，非常值得体验。作为产品研发中心，澳麒的80%产品都在这里进行研发。">
    <meta name="description" content="澳麒产品生产和出口中心Harbour bottling(港口灌装基地)位于阿德莱德最大的出口港区-弗林德斯港。距离弗林德斯港口吊装码头仅1公里。澳州唯一位于港口的葡萄酒罐装工厂，同时也是澳州目前出口最快速度的葡萄酒生产产区。Harbour Bottling 有2400
  平方米的生产车间，以及1200平方米的产品仓储车间，具备仓储，装箱，发货的一站式出口服务功能，具有年生产并出口600个集装箱的生产能力，是澳麒酒业全资拥有。同时在澳州悉尼，墨尔本，布里斯班，珀斯以及中国常州，上海等地均设有办事处，销售网络完善健全。">

    <meta name="author" content="Jetek.com.au | Orchid Wine">
    <meta name="keywords" content="澳麒酒业集团,南澳酒庄，澳洲红酒，灌装厂,澳洲红酒进出口">
    <title>澳麒酒业集团 - 体验纯甄南澳葡萄酒</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- ICO -->
    <link rel="icon" href="orchid_small.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="orchid_small.ico" type="image/x-icon" />

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome/css/all.min.css" rel="stylesheet">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">

    <!-- Custom styles for this template -->
    <link href="css/landing-page.css" rel="stylesheet">
    <link href="css/point.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127062225-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-127062225-1');
    </script>
    <!-- Start of  Zendesk Widget script -->
    <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=89ff1313-e5a4-45b4-9af1-bf10936521ce"> </script>
    <!-- End of  Zendesk Widget script -->

</head>

<body>

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar">
    <div class="container">
        <a class="navbar-brand" href="#"> <img src="./img/logo/group-logo.png" width="auto" height="30" alt="Orchid Wine">
            <strong>
                | 澳麒酒业集团</strong></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#orchidwine">澳麒酒业
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tank">TANK 城市会客厅</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#blickinstal">百乐庄</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#harbourbottling">港口灌装基地</a>
                </li>
        </div>
        </ul>
    </div>
    </div>
    <div class="dropdown">
        <button class="btn  btn-success-outline dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-language" aria-hidden="true"></i>
            &nbsp; 语言 (中文)
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/cn">中文</a>
            <a class="dropdown-item" href="/">English</a>
        </div>
</nav>

<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item active" style="background-image: url('img/slide/Office-1.jpg')">
                <div class="carousel-caption">
                    <a href="https://trade.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/orchid-wine-logo.png"
                                                                   height="100px" alt="Orhcid Wine"></a>
                </div>
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Tank.jpg')">
                <div class="carousel-caption">
                    <a href="https://tank.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/tank-logo-white.png"
                                                                  height="100px" alt="Tank Logo"></a>
                    <p class="lead"> TANK 城市会客厅</p>
                </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Blickinstal.jpg')">
                <div class="carousel-caption">
                    <a href="https://blickinstal.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/blickinstal-logo.png"
                                                                         height="200px" alt="Blickinstal Logo"></a>
                </div>
            </div>
            <!-- Slide Four - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Harbourbottling.jpg')">
                <div class="carousel-caption">
                    <a href="https://harbourbottling.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/harbour-bottling-logo.png"
                                                                             height="100px" alt="Harbour-bottling Logo"></a>

                </div>
            </div>


        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="row no-gutters" id="orchidwine">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-1-1.jpg');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <a href="https://trade.orchidwine.com.au">
                    <h2>澳麒酒业</h2>
                </a>
                <br>
                <h3 class="lead mb-0">位于阿德莱德CBD的澳麒酒业总部，承担着“业务洽谈，产品设计，生产调度，市场推广，企业培训”等业务。
                    <br><br>办公室地处阿德莱德市区的黄金地段，位于阿德莱德Gouger
                    St的208号，占地210平方米，毗邻澳州邮政的物流中心，交通十分便利，距离阿德莱德机场也仅5公里路程，是开展国际贸易的最佳地段。 </p>
            </div>
        </div>
        <div class="row no-gutters" id="tank">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-2.jpg');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <a href="https://tank.orchidwine.com.au">
                    <h2>TANK Cellars - 城市会客厅 </h2>
                </a>
                <br>
                <h3 class="lead mb-0">全球首家TANK Cellars 选址于世界十大葡萄酒之都的阿德莱德。TANK Cellars 成立的初衷，就是为了向全世界的酒类爱好者，更好的介绍和推荐来自于南澳地区的精品葡萄酒，啤酒以及烈酒。 
                    <br><br>南澳，作为一个充满活力的葡萄酒产区，拥有众多世界闻名的子产区，如巴罗莎等。得天独厚的条件，使得这个地区佳酿频出。
                    <br><br>因此，TANK Cellars 致力于向全世界的广大消费者传播南澳的葡萄酒文化以及葡萄酒酿造工艺，与此同时，更是为了将每一款的好酒带到您的面前。</h3>
            </div>
        </div>
        <div class="row no-gutters" id="blickinstal">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-3.jpg');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <a href="https://blickinstal.orchidwine.com.au">
                    <h2>Blickinstal 百乐庄</h2>
                </a>
                <br>
                <h3 class="lead mb-0">澳麒百乐葡萄园及产品研发心Blickinstal，是位于巴罗莎山谷的核心产区酒庄，是澳麒的产品体验以及研发中心。
                    <br><br>Blickinstal民宿，连续3年被澳州评为5星级B&B
                    民宿，非常值得体验。作为产品研发中心，澳麒的80%产品都在这里进行研发。
                </h3>
            </div>
        </div>
        <div class="row no-gutters" id="harbourbottling">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-4.jpg');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <a href="https://harbourbottling.orchidwine.com.au">
                    <h2>港口灌装基地 </h2>
                </a>
                <br>
                <h3 class="lead mb-0">澳麒产品生产和出口中心Harbour
                    bottling(港口灌装基地)位于阿德莱德最大的出口港区-弗林德斯港。距离弗林德斯港口吊装码头仅1公里。
                    <br><br>澳州唯一位于港口的葡萄酒罐装工厂，同时也是澳州目前出口最快速度的葡萄酒生产产区。
                    <br><br>Harbour Bottling 有2400
                    平方米的生产车间，以及1200平方米的产品仓储车间，具备仓储，装箱，发货的一站式出口服务功能，具有年生产并出口600个集装箱的生产能力，是澳麒酒业全资拥有。
                    <br><br>同时在澳州悉尼，墨尔本，布里斯班，珀斯以及中国常州，上海等地均设有办事处，销售网络完善健全。
                </h3>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white mobile-map" style="background-image: url('img/map-au-mobile.png');"></div>
        </div>
    </div>
</section>

<!-- Call to Action -->
<section class="call-to-action text-white text-center">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-xl-9 mx-auto">
                <h2 class="mb-4">Orchid Group</h2>
            </div>
            <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
            </div>
        </div>
    </div>
</section>

<!-- MAP -->
<section class="call-to-action text-white text-center">
    <div class="y-row y-clear" style="position: relative;">
        <div class="main-img" id="serve-img-area" style="position: relative;">
            <img src="img/map-au-1.png" alt="AU-map" style="height:500px">
            <div class="point-area point-p" style="top: 300px; left: 600px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 85px;">阿德莱德</p>
                <a class="point point-dot"></a>
                <div class="point point-10"></div>
                <div class="point point-40"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 350px; left: 660px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 85px;">墨尔本</p>
                <a class="point point-dot"></a>
                <div class="point point-10"></div>
                <div class="point point-40"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 250px; left: 320px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 100px;">珀斯</p>
                <a class="point point-dot"></a>
                <div class="point point-40"></div>
                <div class="point point-10"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 200px; left: 750px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 85px;">布里斯班</p>
                <a class="point point-dot"></a>
                <div class="point point-40"></div>
                <div class="point point-10"></div>
                <div class="point point-shadow point-80"></div>
            </div>
        </div>
        <div class="main-bar">
        </div>
    </div>
</section>
<!-- Map -->


<!-- Footer -->
<footer class="page-footer font-small unique-color-dark" style="background-color: #5a5d60;">

    <div>
        <div class="container">
            <br><br>
        </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

        <!-- Grid row -->
        <div class="row mt-3">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mb-4">
                <h2 style="color:white">联系我们 : </h2>
                <!-- <a href="https://orchidwine.com.au"><img src="img/logo/orchid-group-en.png" height="80" width="149" onMouseOver="this.src='img/logo/orchid-group-en-red.png' "  onMouseOut="this.src='img/logo/orchid-group-en.png' "></a> -->
            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 "></div>
            <div class="col-md-2 col-lg-2 col-xl-2 "></div>
            <div class="col-md-2 col-lg-2 col-xl-2 "></div>

        </div>
        <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

                <!-- Links -->
                <a data-toggle="modal" data-target="#OrchidWineContact"> <img src="img/logo/orchid-wine-logo.png" height="80"
                                                                              width="149" alt="Orchid IMG" onMouseOver="this.src='img/logo/orchid-wine-logo-red.png' " onMouseOut="this.src='img/logo/orchid-wine-logo.png' "></a>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 ">

                <!-- Links -->

                <a data-toggle="modal" data-target="#TankContact" href="https://tank.orchidwine.com.au"><img src="img/logo/tank-logo-white.png"
                                                                                                             height="80" width="170" alt="Tank IMG" onMouseOver="this.src='img/logo/tank-logo-white-red.png' "
                                                                                                             onMouseOut="this.src='img/logo/tank-logo-white.png' "></a>

            </div>
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->

                <a data-toggle="modal" data-target="#BlickinstalContact" href="https://blickinstal.orchidwine.com.au"><img
                            src="img/logo/blickinstal-logo.png" height="80" width="149" alt="Blickinstal IMG" onMouseOver="this.src='img/logo/blickinstal-logo-red.png' "
                            onMouseOut="this.src='img/logo/blickinstal-logo.png' "></a>
            </div>

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-md-0 mb-4">

                <!-- Links -->
                <a data-toggle="modal" data-target="#HarbourBottlingContact" href="https://harbourbottling.orchidwine.com.au"><img
                            src="img/logo/harbour-bottling-logo.png" height="80" alt="Harbour Bottling IMG" onMouseOver="this.src='img/logo/harbour-bottling-logo-red.png' "
                            onMouseOut="this.src='img/logo/harbour-bottling-logo.png' "></a>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
        <div>
            <br><br>
        </div>
        <!-- Grid row -->
    </div>

    <!-- Orchid Wine Modal -->
    <div class="modal fade" id="OrchidWineContact" tabindex="-1" role="dialog" aria-labelledby="OrchidWineContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="OrchidWineContact">澳麒酒业 - 联系我们 </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Head Office  -->
                    <p style="color: #ef3d3d"> <b>总部联系方式</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 208 Gouger Street, Adelaide, SA 5000</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://trade.orchidwine.com.au">https://trade.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@orchidwine.com.au">info@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0884104635">＋61 8 8410 4635</a></p>
                </div>
                <!-- Melbourne Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>墨尔本 办公室</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> Unit 42/31-39 Norcal Road Nunawading, VIC 3131</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:info.mel@orchidwine.com.au">info.mel@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0388381017">+61 3 88381017</a></p>
                </div>
                <!-- Perth Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>珀斯 办公室</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 6 Birchgrove Court, Bibra Lake, WA, 6163</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:stella.w@orchidwine.com.au">stella.w@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0448066101">+61 448 066 101</a></p>
                </div>
                <!-- Brisbane Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>布里斯班 办公室</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 150 Didbrook st，Robertson，QLD, 4109</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:johnny.chen@orchidwine.com.au">johnny.chen@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0422556888">+61 422 556 888</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <!-- <button type="button" class="btn btn-primary"><a href="tel:＋61 8 8410 4635" style="color:white">Call us</a></button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- Orchid Wine Modal -->

    <!-- Tank Modal -->
    <div class="modal fade" id="TankContact" tabindex="-1" role="dialog" aria-labelledby="TankContact" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="TankContact">TANK 城市会客厅 - 联系我们 </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 135 Gouger St, Adelaide, SA 5000</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://tank.orchidwine.com.au">https://tank.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@orchidtank.com.au">info@orchidtank.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0882215000">＋61 8 8221 5000</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:0882215000" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Tank  Modal -->

    <!-- Blickinstal Modal -->
    <div class="modal fade" id="BlickinstalContact" tabindex="-1" role="dialog" aria-labelledby="BlickinstalContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="BlickinstalContact">Blickinstal 百乐庄 - 联系我们 </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 261 Rifle Range Road, Benthany, SA 5352</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://blickinstal.orchidwine.com.au">https://blickinstal.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:admin@blickinstal.com.au">admin@blickinstal.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0885632716">+61 8 8563 2716</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:0885632716" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Blickinstal Modal -->

    <!-- Harbour Bottling Modal -->
    <div class="modal fade" id="HarbourBottlingContact" tabindex="-1" role="dialog" aria-labelledby="HarbourBottlingContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="HarbourBottlingContact">港口灌装基地 - 联系我们 </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 18 Annie Watt Circuit, Osborne, SA 5017</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://harbourbottling.orchidwine.com.au">https://harbourbottling.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@harbourbottling.com">info@harbourbottling.com</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0883419999">＋61 8 8341 9999</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:0883419999" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Harbour Bottling Modal -->

    <!-- Copyright -->
    <div class="footer bg-light text-center py-3">
        <p class="text-muted small mb-4 mb-lg-0">&copy; 2013 - <span id="year"></span> 澳麒酒业集团版权所有 <br>
            <a href="https://trade.orchidwine.com.au/cn#business">关于我们</a>  |
            设计: <a href="http://orchidwine.com.au"> 澳麒酒业信息中心 </a></p>
    </div>
    <script>
        document.getElementById('year').innerHTML = new Date().getFullYear() + '';
    </script>
    <!-- Copyright -->

</footer>
<!-- Footer -->

<!-- Bootstrap core JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>

</html>