
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
  [ {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "Orchid Wine",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "Tank Cellars",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "Blickinstal",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  }, {
    "@context" : "http://schema.org",
    "@type" : "Product",
    "name" : "Orchid Group",
    "image" : [ "https://www.orchidwine.com.au/img/bg-1-1.jpg", "https://www.orchidwine.com.au/img/bg-2.jpg", "https://www.orchidwine.com.au/img/bg-3.jpg", "https://www.orchidwine.com.au/img/bg-4.jpg" ],
    "brand" : {
      "@type" : "Brand",
      "name" : "Harbour Bottling",
      "logo" : "https://www.orchidwine.com.au/img/logo/group-logo.png"
    }
  } ]
  </script>
    <meta name="description" content="Orchid Group |Wine Estate |Tank |Blickinstal |Harbour Bottling |Orchid Group Home | 澳麒集团首页">
    <meta name="description" content="Orchid Group |澳麒酒业 |TANK 城市会客厅 |百乐庄 |港口灌装基地 |Orchid Group Home | 澳麒集团首页">
    <meta name="description" content=" CBD office located in Adelaide CBD, and next to Australian logistic center, 5 km away
  from Adelaide Airport. Main Functions: Business Negotiation, Product Design, Producrion Coordination,
  Marketing Strategy Planning, Enterprise Training. ">
    <meta name="description" content="The first Tank Cellars established in Adelaide, one of the top 10 wine capitals of
  the world. The main purpose of opening the TANK cellar door is to showcase the premium products of Australia and boutique South Australian wine, beer and spirits. South Australia is a dynamic wine region, with a group of passionate and creative winemakers that are
  running many experimental winemaking programs actively and created a bunch of distinguished and outstanding products.We aim to use TANK as a platform to
  spread South Australian wine culture and winemaking philosophies to the world, at the same time to bring
  great Australian food to consumers world widely.">
    <meta name="description" content="Located in the major wine region Barossa in SA. It is also the wine tasting and wine
  product research center. 80% of Orchid wines developed here. Blickinstal Barossa Valley Retreat has been
  rated the No.1 best-rated hotel in Barossa Valley. It also came fourth in the state in the Trivago Awards
  2017.">
    <meta name="description" content="Harbour Bottling lies in Osborne just 1 km from the state’s main export hub. 100% owned
  by Orchid Wine Estate.It is the only bottling factory in Australia located so close to the export hub. The
  workshop is about 2400 square meters warehouse, one-stop service center with multifunction of storage,
  packing and shipping. Annual production capacity: 600 containers.">

    <meta name="author" content="Orchid Wine IT department | Orchid Wine">
    <meta name="keywords" content="Orchid Wine, Group, South Australia Wine, Australia wine outimport,China Wine">
    <title>Orchid Wine Group - Wine Expert from South Australia </title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- ICO -->
    <link rel="icon" href="orchid_small.ico" type="image/x-icon" />
    <link rel="shortcut icon" href="orchid_small.ico" type="image/x-icon" />

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome/css/all.min.css" rel="stylesheet">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">
    <!-- Custom styles for this template -->
    <link href="css/landing-page.css" rel="stylesheet">
    <link href="css/point.css" rel="stylesheet">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127062225-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());
        gtag('config', 'UA-127062225-1');
    </script>
    <!-- Start of  Zendesk Widget script -->
    <script id="ze-snippet" src="https://static.zdassets.com/ekr/snippet.js?key=89ff1313-e5a4-45b4-9af1-bf10936521ce"> </script>
    <!-- End of  Zendesk Widget script -->

</head>

<body>

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light scrolling-navbar">
    <div class="container">
        <h1 class="navbar-brand" href="#"> <img src="./img/logo/group-logo.png" width="auto" height="30" alt="Orchid Wine">
            <strong>
                | Orchid
                Group</strong></h1>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#orchidwine">Orchid Wine
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#tank">Tank Cellars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#blickinstal">Blickinstal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#harbourbottling">Harbour Bottling</a>
                </li>
        </div>
        </ul>
    </div>
    </div>
    <div class="dropdown">
        <button class="btn  btn-success-outline dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-language" aria-hidden="true"></i>
            &nbsp; Language (EN)
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="/">EN</a>
            <a class="dropdown-item" href="/cn">中文</a>
        </div>
</nav>

<header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <!-- <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        </ol> -->
        <div class="carousel-inner" role="listbox">
            <!-- Slide One - Set the background image for this slide in the line below -->
            <div class="carousel-item active" style="background-image: url('img/slide/Office-1.jpg')">
                <div class="carousel-caption">
                    <!-- <h1 class="mb-5">Orchid Wine Estate</h1> -->
                    <a href="https://trade.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/orchid-wine-logo.png"
                                                                   alt="Orhcid Wine"></a>
                    <!-- <p class="lead">Orchid Wine is a good place </p> -->
                </div>
            </div>
            <!-- Slide Two - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Tank1.jpg')">
                <div class="carousel-caption">
                    <a href="https://tank.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/tank-logo-white.png"
                                                                  alt="Tank Logo"></a>
                </div>
            </div>
            <!-- Slide Three - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Blickinstal.jpg')">
                <div class="carousel-caption">
                    <a href="https://blickinstal.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/blickinstal-logo.png"
                                                                         alt="Blickinstal Logo"></a>
                    <!-- <p class="lead">Blickinstal Introduction</p> -->
                </div>
            </div>
            <!-- Slide Four - Set the background image for this slide in the line below -->
            <div class="carousel-item" style="background-image: url('img/slide/Harbourbottling.jpg')">
                <div class="carousel-caption">
                    <a href="https://harbourbottling.orchidwine.com.au"><img class="img-silder-logo" src="img/logo/harbour-bottling-logo.png"
                                                                             alt="Harbour-bottling Logo"></a>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</header>
<section class="showcase">
    <div class="container-fluid p-0">
        <div class="row no-gutters" id="orchidwine">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-1-1.jpg');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <a href="https://trade.orchidwine.com.au">
                    <h2>Orchid Wine Estate</h2>
                </a>
                <br>
                <h3 class="lead mb-0">
                    CBD office located in Adelaide CBD, and next to Australian logistic center, 5 km away
                    from Adelaide Airport.
                    <br><br>
                    Main Functions: Business Negotiation, Product Design, Producrion Coordination,
                    Marketing Strategy Planning, Enterprise Training. </h3>
            </div>
        </div>
        <div class="row no-gutters" id="tank">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-2.jpg');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <a href="https://tank.orchidwine.com.au">
                    <h2>Tank Cellars </h2>
                </a>
                <br>
                <h3 class="lead mb-0">TANK Cellars established in Adelaide, one of the top 10 Wine Capital cities of the world.
                    <br><br>
                    The main purpose of opening TANK Cellars is to showcase the premium products and boutique brands of South Australian Wine and Spirits.
                    <br><br>
                    We aim to use TANK Cellars as a platform to spread South Australian wine culture and winemaking philosophies to the world, at the same time to bring great Australian food to consumers world widely.</h3>
            </div>
        </div>
        <div class="row no-gutters" id="blickinstal">
            <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image: url('img/bg-3.jpg');"></div>
            <div class="col-lg-6 order-lg-1 my-auto showcase-text">
                <a href="https://blickinstal.orchidwine.com.au">
                    <h2>Blickinstal</h2>
                </a>
                <br>
                <h3 class="lead mb-0">Located in the major wine region Barossa in SA. It is also the wine tasting and wine
                    product research center. 80% of Orchid wines developed here.
                    <br><br>
                    Blickinstal Barossa Valley Retreat has been
                    rated the No.1 best-rated hotel in Barossa Valley. It also came fourth in the state in the Trivago Awards
                    2017.
                </h3>
            </div>
        </div>
        <div class="row no-gutters" id="harbourbottling">
            <div class="col-lg-6 text-white showcase-img" style="background-image: url('img/bg-4.jpg');"></div>
            <div class="col-lg-6 my-auto showcase-text">
                <a href="https://harbourbottling.orchidwine.com.au">
                    <h2>Harbour Bottling </h2>
                </a>
                <br>
                <h3 class="lead mb-0">Harbour Bottling lies in Osborne just 1 km from the state’s main export hub. 100% owned
                    by Orchid Wine Estate.
                    <br><br>
                    It is the only bottling factory in Australia located so close to the export hub. The
                    workshop is about 2400 square meters warehouse, one-stop service center with multifunction of storage,
                    packing and shipping. Annual production capacity: 600 containers. </h3>
            </div>
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6 text-white mobile-map" style="background-image: url('img/map-au-mobile.png');"></div>
        </div>
    </div>
</section>


<!-- MAP -->
<section class="call-to-action text-white text-center">
    <div class="y-row y-clear" style="position: relative;">
        <div class="main-img" id="serve-img-area" style="position: relative;">
            <img src="img/map-au-1.png" alt="AU-map" style="height:500px">
            <div class="point-area point-p" style="top: 300px; left: 600px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 100px;">Adelaide</p>
                <a class="point point-dot"></a>
                <div class="point point-10"></div>
                <div class="point point-40"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 350px; left: 660px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 100px;">Melbourne</p>
                <a class="point point-dot"></a>
                <div class="point point-40"></div>
                <div class="point point-10"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 250px; left: 320px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 100px;">Perth</p>
                <a class="point point-dot"></a>
                <div class="point point-40"></div>
                <div class="point point-10"></div>
                <div class="point point-shadow point-80"></div>
            </div>
            <div class="point-area point-p" style="top: 200px; left: 750px; position: absolute; width: 150px; height: 150px; visibility: visible; opacity: 1;">
                <p class="point-name" style="position: absolute; top: 65px; left: 100px;">Brisbane</p>
                <a class="point point-dot"></a>
                <div class="point point-40"></div>
                <div class="point point-10"></div>
                <div class="point point-shadow point-80"></div>
            </div>
        </div>
        <div class="main-bar">
        </div>
    </div>
</section>
<!-- Map -->



<!-- Footer -->
<footer class="page-footer font-small unique-color-dark" style="background-color: #5a5d60;">

    <div>
        <div class="container">
            <br><br>
        </div>
    </div>

    <!-- Footer Links -->
    <div class="container text-center text-md-left mt-5">

        <!-- Grid row -->
        <div class="row mt-3">

            <!-- Grid column -->
            <div class="col-md-3 col-lg-3 col-xl-3 mb-4">
                <h2 style="color:white">Contact us : </h2>
                <!-- <a href="https://orchidwine.com.au"><img src="img/logo/orchid-group-en.png" height="80" width="149" onMouseOver="this.src='img/logo/orchid-group-en-red.png' "  onMouseOut="this.src='img/logo/orchid-group-en.png' "></a> -->
            </div>

            <div class="col-md-2 col-lg-2 col-xl-2"></div>
            <div class="col-md-2 col-lg-2 col-xl-2"></div>
            <div class="col-md-2 col-lg-2 col-xl-2"></div>

        </div>
        <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

                <!-- Links -->
                <a data-toggle="modal" data-target="#OrchidWineContact"> <img src="img/logo/orchid-wine-logo.png" height="80"
                                                                              width="170" alt="Orchid IMG" onMouseOver="this.src='img/logo/orchid-wine-logo-red.png' " onMouseOut="this.src='img/logo/orchid-wine-logo.png' "></a>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 ">

                <!-- Links -->

                <a data-toggle="modal" data-target="#TankContact" href="https://tank.orchidwine.com.au"><img src="img/logo/tank-logo-white.png"
                                                                                                             height="80" width="170" alt="Tank IMG" onMouseOver="this.src='img/logo/tank-logo-white-red.png' "
                                                                                                             onMouseOut="this.src='img/logo/tank-logo-white.png' "></a>

            </div>
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->

                <a data-toggle="modal" data-target="#BlickinstalContact" href="https://blickinstal.orchidwine.com.au"><img
                            src="img/logo/blickinstal-logo.png" height="80" width="170" alt="Blickinstal IMG" onMouseOver="this.src='img/logo/blickinstal-logo-red.png' "
                            onMouseOut="this.src='img/logo/blickinstal-logo.png' "></a>

            </div>

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-md-0 mb-4">

                <!-- Links -->
                <a data-toggle="modal" data-target="#HarbourBottlingContact" href="https://harbourbottling.orchidwine.com.au"><img
                            src="img/logo/harbour-bottling-logo.png" height="80" width="170" alt="Harbour Bottling IMG" onMouseOver="this.src='img/logo/harbour-bottling-logo-red.png' "
                            onMouseOut="this.src='img/logo/harbour-bottling-logo.png' "></a>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
        <div>
            <br><br>
        </div>
        <!-- Grid row -->
    </div>

    <!-- Orchid Wine Modal -->
    <div class="modal fade" id="OrchidWineContact" tabindex="-1" role="dialog" aria-labelledby="OrchidWineContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="OrchidWineContact">Orchid Wine - Contact us </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <!-- Head Office  -->
                    <p style="color: #ef3d3d"> <b>Head Office</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 208 Gouger Street, Adelaide, SA 5000</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://trade.orchidwine.com.au">https://trade.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@orchidwine.com.au">info@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0884104635">＋61 8 8410 4635</a></p>
                </div>
                <!-- Melbourne Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>Melbourne Office</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> Unit 42/31-39 Norcal Road Nunawading, VIC 3131</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:info.mel@orchidwine.com.au">info.mel@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0388381017">+61 3 88381017</a></p>
                </div>
                <!-- Perth Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>Perth Office</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 6 Birchgrove Court, Bibra Lake, WA6163</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:stella.w@orchidwine.com.au">stella.w@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0448066101">+61 448 066 101</a></p>
                </div>
                <!-- Brisbane Office -->
                <div class="modal-body">
                    <p style="color: #ef3d3d"> <b>Brisbane Office</b> </p>
                    <p>
                        <i class="fa fa-home mr-3"></i> 150 Didbrook st，Robertson，QLD, 4109</p>
                    <i class="fa fa-envelope mr-3"></i> <a href="mailto:johnny.chen@orchidwine.com.au">johnny.chen@orchidwine.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0422556888">+61 422 556 888</a></p>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <!-- <button type="button" class="btn btn-primary"><a href="tel:＋61 8 8410 4635" style="color:white">Call us</a></button> -->
                </div>
            </div>
        </div>
    </div>
    <!-- Orchid Wine Modal -->

    <!-- Tank Modal -->
    <div class="modal fade" id="TankContact" tabindex="-1" role="dialog" aria-labelledby="TankContact" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="TankContact">Tank Cellars - Contact us </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 135 Gouger St, Adelaide, SA 5000</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://tank.orchidwine.com.au">https://tank.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@orchidtank.com.au">info@orchidtank.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0882215000">＋61 8 8221 5000</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:＋0882215000" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Tank  Modal -->

    <!-- Blickinstal Modal -->
    <div class="modal fade" id="BlickinstalContact" tabindex="-1" role="dialog" aria-labelledby="BlickinstalContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="BlickinstalContact">Blickinstal - Contact us </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 261 Rifle Range Road, Benthany, SA 5352</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://blickinstal.orchidwine.com.au">https://blickinstal.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:admin@blickinstal.com.au">admin@blickinstal.com.au</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0885632716">+61 8 8563 2716</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:0885632716" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Blickinstal Modal -->

    <!-- Harbour Bottling Modal -->
    <div class="modal fade" id="HarbourBottlingContact" tabindex="-1" role="dialog" aria-labelledby="HarbourBottlingContact"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="HarbourBottlingContact">Harbour Bottling - Contact us </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        <i class="fa fa-home mr-3"></i> 18 Annie Watt Circuit, Osborne, SA 5017</p>
                    <p>
                        <i class="fas fa-globe-americas mr-3"></i> <a href="https://harbourbottling.orchidwine.com.au">https://harbourbottling.orchidwine.com.au
                        </a></p>
                    <p>
                        <i class="fa fa-envelope mr-3"></i> <a href="mailto:info@harbourbottling.com">info@harbourbottling.com</a></p>
                    <p>
                        <i class="fa fa-phone mr-3"></i> <a href="tel:0883419999">＋61 8 8341 9999</a></p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary"><a href="tel:0883419999" style="color:white">Call us</a></button>
                </div>
            </div>
        </div>
    </div>
    <!-- Harbour Bottling Modal -->

    <!-- Copyright -->
    <div class="footer bg-light text-center py-3">
        <p class="text-muted small mb-4 mb-lg-0">&copy; 2013 - <span id="year"></span> Orchid Wine Estate All Rights Reserved

            <br>
            <a href="https://trade.orchidwine.com.au/#business">About</a> | <a href="https://trade.orchidwine.com.au/#business">Terms & Conditions</a>
            <br>
            Designed by <a href="team/IT">Orchid Wine Estate IT department</a>
        </p>
    </div>
    <script>
        document.getElementById('year').innerHTML = new Date().getFullYear() + '';
    </script>
    <!-- Copyright -->

</footer>
<!-- Footer -->

<!-- Bootstrap core JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>

</html>